// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/douyu/jupiter-layout/internal/app/exampleserver/controller"
	"github.com/douyu/jupiter-layout/internal/app/exampleserver/service"
	"github.com/douyu/jupiter-layout/internal/pkg/grpc"
	"github.com/douyu/jupiter/pkg/application"
)

// Injectors from wire.go:

func InitApp(app *application.Application) error {
	exampleInterface := grpc.NewExample()
	options := service.Options{
		ExampleGrpc: exampleInterface,
	}
	helloWorld := service.NewHelloWorldService(options)
	helloWorldHTTP := controller.NewHelloWorldHTTPController(helloWorld)
	helloWorldGRPC := controller.NewHelloWorldGRPCController(helloWorld)
	controllerOptions := controller.Options{
		HelloWorldHTTP: helloWorldHTTP,
		HelloWorldGRPC: helloWorldGRPC,
	}
	httpServer := NewHttpServer(controllerOptions)
	grpcServer := NewGrpcServer(controllerOptions)
	serverOptions := Options{
		http: httpServer,
		grpc: grpcServer,
	}
	error2 := initApp(app, serverOptions)
	return error2
}
