// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/douyu/jupiter-layout/internal/app/exampleserver/controller"
	"github.com/douyu/jupiter-layout/internal/app/exampleserver/service"
	"github.com/douyu/jupiter-layout/internal/pkg/grpc"
	"github.com/douyu/jupiter-layout/internal/pkg/mysql"
	"github.com/douyu/jupiter-layout/internal/pkg/redis"
	"github.com/douyu/jupiter-layout/internal/pkg/resty"
	"github.com/douyu/jupiter-layout/internal/pkg/rocketmq"
	"github.com/douyu/jupiter/pkg/core/application"
)

// Injectors from wire.go:

func InitApp(app *application.Application) error {
	exampleInterface := grpc.NewExample()
	mysqlExampleInterface := mysql.NewExample()
	redisExampleInterface := redis.NewExample()
	restyExampleInterface := resty.NewExample()
	rocketmqExampleInterface := rocketmq.NewInstance()
	options := service.Options{
		ExampleGrpc:     exampleInterface,
		ExampleMysql:    mysqlExampleInterface,
		ExampleRedis:    redisExampleInterface,
		ExampleResty:    restyExampleInterface,
		ExampleRocketMQ: rocketmqExampleInterface,
	}
	helloWorld := service.NewHelloWorldService(options)
	helloWorldHTTP := controller.NewHelloWorldHTTPController(helloWorld)
	helloWorldGRPC := controller.NewHelloWorldGRPCController(helloWorld)
	controllerOptions := controller.Options{
		HelloWorldHTTP: helloWorldHTTP,
		HelloWorldGRPC: helloWorldGRPC,
	}
	httpServer := NewHttpServer(controllerOptions)
	grpcServer := NewGrpcServer(controllerOptions)
	server := NewGovernServer()
	rocketMQ := NewRocketMQ()
	serverOptions := Options{
		http:     httpServer,
		grpc:     grpcServer,
		govern:   server,
		rocketmq: rocketMQ,
	}
	error2 := initApp(app, serverOptions)
	return error2
}
