// Code generated by struct2interface; DO NOT EDIT.

package grpc

import (
	"context"

	helloworldv1 "github.com/douyu/jupiter-layout/gen/api/go/helloworld/v1"
)

// ExampleInterface ...
type ExampleInterface interface {
	SayHello(ctx context.Context, req *helloworldv1.SayHelloRequest) (*helloworldv1.SayHelloResponse, error)
}
