// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/douyu/jupiter-layout/internal/pkg/grpc"
)

// Injectors from wire.go:

func createMockHelloWorldService() *HelloWorld {
	exampleInterface := grpc.NewExample()
	options := Options{
		ExampleGrpc: exampleInterface,
	}
	helloWorld := NewHelloWorldService(options)
	return helloWorld
}
