run:
  timeout: 5m
  tests: false

  skip-dirs:
    - .go/

  skip-files:
    - ".*pb.go"

  sort-results: true
  go: "1.17"

linters:
  enable:
    # - deadcode
    - govet
    - ineffassign
    - staticcheck
    # - structcheck
    - typecheck
    - unused
    # - varcheck
    - bodyclose
    - depguard
    - goconst
    - gofmt
    - goimports
    - gosec
    - misspell
    - prealloc
    - unconvert

linters-settings:
  depguard:
    deny:
      - pkg: "github.com/sirupsen/logrus"
        desc: not allowed
      - pkg: "github.com/pkg/errors"
        desc: Should be replaced by standard lib errors package
