version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - cache:/data
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jupiter

  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001

volumes:
  db:
    driver: local
  cache:
    driver: local

