version: '3.3'

# jaeger: http://localhost:16686
# prometheus: http://localhost:9090
# grafana: http://localhost:3000
# juno-admin: http://localhost:50002

services:
  exampleserver:
    build:
      context: .
      dockerfile: ./cmd/exampleserver/Dockerfile
    restart: always
    volumes:
      - .:/src
    network_mode: host