// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package e2e

import (
	"github.com/douyu/jupiter-layout/internal/app/exampleserver/service"
	"github.com/douyu/jupiter-layout/internal/pkg/grpc"
	"github.com/douyu/jupiter-layout/internal/pkg/mysql"
	"github.com/douyu/jupiter-layout/internal/pkg/redis"
	"github.com/douyu/jupiter-layout/internal/pkg/resty"
	"github.com/douyu/jupiter-layout/internal/pkg/rocketmq"
)

// Injectors from wire.go:

func CreateExampleService() *service.HelloWorld {
	exampleInterface := grpc.NewExample()
	mysqlExampleInterface := mysql.NewExample()
	redisExampleInterface := redis.NewExample()
	restyExampleInterface := resty.NewExample()
	rocketmqExampleInterface := rocketmq.NewInstance()
	options := service.Options{
		ExampleGrpc:     exampleInterface,
		ExampleMysql:    mysqlExampleInterface,
		ExampleRedis:    redisExampleInterface,
		ExampleResty:    restyExampleInterface,
		ExampleRocketMQ: rocketmqExampleInterface,
	}
	helloWorld := service.NewHelloWorldService(options)
	return helloWorld
}
