// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExampleInterface is an autogenerated mock type for the ExampleInterface type
type ExampleInterface struct {
	mock.Mock
}
