apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: curlimages/curl:7.88.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl http://exampleserver:9527/v1/helloworld.Greeter/SayHello/bob
          restartPolicy: OnFailure