apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../exampleserver

patches:

  - target:
      kind: Service
    path: local_service.yaml
  - target:
      kind: Deployment
    path: local_deployment.yaml
   