apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../exampleserver"
  - "./cronjob.yaml"

patches:

  - target:
      kind: Deployment
    path: local_deployment.yaml
   