apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleserver
  labels:
    name: exampleserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exampleserver
  strategy: {}
  template:
    metadata:
      labels:
        runEnv: dev
    spec:
      containers:
        - name: exampleserver
          command: ["/app/exampleserver", "--config", "etcdv3://etcd:2379/juno-agent/cluster/exampleserver/dev/static/config-dev.toml"]
