---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f deployment/docker-compose-for-k8s.yml -o deployment/install.yml
    kompose.version: 1.28.0 (HEAD)
    kompose.volume.type: configMap
  creationTimestamp: null
  labels:
    io.kompose.service: juiter-layout
  name: juiter-layout
spec:
  ports:
    - name: "9527"
      port: 9527
      targetPort: 9527
    - name: "9528"
      port: 9528
      targetPort: 9528
    - name: "9529"
      port: 9529
      targetPort: 9529
  selector:
    io.kompose.service: juiter-layout
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f deployment/docker-compose-for-k8s.yml -o deployment/install.yml
    kompose.version: 1.28.0 (HEAD)
    kompose.volume.type: configMap
  creationTimestamp: null
  labels:
    io.kompose.service: juiter-layout
  name: juiter-layout
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: juiter-layout
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f deployment/docker-compose-for-k8s.yml -o deployment/install.yml
        kompose.version: 1.28.0 (HEAD)
        kompose.volume.type: configMap
      creationTimestamp: null
      labels:
        io.kompose.network/deployment-default: "true"
        io.kompose.service: juiter-layout
    spec:
      containers:
        - image: ghcr.io/douyu/jupiter-layout:latest
          name: juiter-layout
          ports:
            - containerPort: 9527
            - containerPort: 9528
            - containerPort: 9529
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: deployment-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/deployment-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/deployment-default: "true"

