// Code generated by mockery v2.19.0. DO NOT EDIT.

package rocketmq

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExampleInterface is an autogenerated mock type for the ExampleInterface type
type MockExampleInterface struct {
	mock.Mock
}

// PushExampleMessage provides a mock function with given fields: ctx
func (_m *MockExampleInterface) PushExampleMessage(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockExampleInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockExampleInterface creates a new instance of MockExampleInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockExampleInterface(t mockConstructorTestingTNewMockExampleInterface) *MockExampleInterface {
	mock := &MockExampleInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
