// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExampleInterface is an autogenerated mock type for the ExampleInterface type
type ExampleInterface struct {
	mock.Mock
}

// SayHello provides a mock function with given fields: ctx
func (_m *ExampleInterface) SayHello(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
