// Code generated by github.com/douyu/jupiter/cmd/protoc-gen-go-xerror. DO NOT EDIT.
// versions:
// - protoc-gen-go-xerror v0.11.0
// - protoc             (unknown)

package helloworldv1

import (
	xerror "github.com/douyu/jupiter/pkg/util/xerror"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the github.com/douyu/jupiter/cmd/protoc-gen-go-xerror package it is being compiled against.
var _ = new(xerror.Err)
