// Code generated by mockery v2.10.4. DO NOT EDIT.

package redis

import mock "github.com/stretchr/testify/mock"

// MockExampleInterface is an autogenerated mock type for the ExampleInterface type
type MockExampleInterface struct {
	mock.Mock
}
