apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "deployment.yaml"
  - "service.yaml"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: exampleserver-config
  files:
  - config/local-k8s.toml
