name: buf-lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'api'
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'api'
          # The 'main' branch of the GitHub repository that defines the module.
          # Note we specify the subdir to compare against.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=api'